### ISSUE TITLE
fix tus client integration

### ISSUE THREAD

**Issue by robmcguinness** [Availity/sdk-js#101]
https://github.com/tus/tus-js-client/issues/137

1. move `this.isValidFile())` to contructor and out of `success()` and `error()` callbacks
2. calculate full url using base url 

```js
const location = window.location.href; 
const pathname = window.location.pathname; 

const index = location.indexOf(pathname);

const base = location.substring(0, index);

....


const defaultOptions = {
  endpoint: `${base}...`
}
````

**Comment by TheSharpieOne** [comment]
#77 seems related since this is mostly the reason I opened it as I foresaw this issue.

**Comment by robmcguinness** [comment]
ah...will handle #77 as well. muchas gracias **TheOracleOne** aka @TheSharpieOne
