### ISSUE TITLE
Gatsby Umbrella Issue

### ISSUE THREAD

**Issue by GoPro16** [Availity/sdk-js#136]
## Gatsby Docs Site

Creating this umbrella issue until we are satisfied with the way the docs are structured for this package.

Target Structure:
https://availity.github.io/sdk-js will point to the gatsby site.

The exact side navigation is up in the air still but its currently formatted with the way the current docs are written.

Instead of documenting each of these as their own package we need to think more on what the end implementation is going to look like and refactor the docs to look like that. 

For example, when a develop wants to use the `avOrganizationsApi` in their web app, they technically are going to use the `@availity/api-axios` package but under the hood the definitions are logic is nested in the `@availity/api-core` package. With that it would be easier to structure all `@availity/api-core` resources under one dropdown and have some section in there that explains how to use the resources in a web app. Furthermore we should be including possible response structures of each resource. We do this for internal docs, as well as provide mock data in `@availity/mock-data` so it should also be showcased here as well.

Refactor Todos:
- [ ] API Resources
  - [ ] Core/Axios
  - [ ] Definitions
  - [ ] Authorizations
  - [ ] Downloads
  - [ ] Uploads
- [ ] Messaging
- [ ] Env Vars
- [ ] Native Form
- [ ] Resolve Url
- [ ] Analytics
- [ ] Yup Extensions
- [ ] Exceptions

**Comment by robmcguinness** [comment]
Is this still relevant?

**Comment by GoPro16** [comment]
As far as getting it created this is complete. The biggest challenge now is writing them in a friendly format
