### ISSUE TITLE
Allow passing userId to getOrganizations

### ISSUE THREAD

**Issue by jordan-a-young** [Availity/sdk-js#147]
### Current Behavior

The method `getOrganizations` from `AvOrganizationsApi` currently fetches the user every time it is called. This requires an unnecessary call to be made if I have already fetched the current user.

### Desired Behavior

I want to be able to pass in the `userId` to limit the need to call `AvUserApi.me`.

### Suggested Solution

Allow `userId` to be passed in as a param or a property of the config.

### Who does this impact? Who is this for?

This will have the greatest impact on applications running inside the Availity portal, but will benefit anyone who already has a userId. This should also limit unnecessary calls. This could open up a security hole however, if the reason for the call is to ensure the currently logged in userId is being used.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by GoPro16** [comment]
I think this would be a great feature for minimizing the amount of requests.

Correct me if I am wrong, but I believe the `users` api call only gets called once for the `organizationsApi` and then every subsequent call doesn't hit that endpoint first. I think the cache is handling that part for the user.

**Comment by nylon22** [comment]
> This could open up a security hole however, if the reason for the call is to ensure the currently logged in userId is being used.

`userId` is validated server side so no security concerns 👍 

> Correct me if I am wrong, but I believe the users api call only gets called once for the organizationsApi and then every subsequent call doesn't hit that endpoint first. I think the cache is handling that part for the user.

You are correct @GoPro16 . Subsequent requests are pulled from browser cache.

**Comment by jordan-a-young** [comment]
> `userId` is validated server side so no security concerns
I was hoping that was the case.

> Correct me if I am wrong, but I believe the users api call only gets called once for the organizationsApi and then every subsequent call doesn't hit that endpoint first. I think the cache is handling that part for the user.
That makes me feel better. My network tab shows multiple calls so I was concerned about eating up unnecessary resources.

**Comment by jordan-a-young** [comment]
https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/resources/organizations.js#L20

Looking again, if I really need to, I could just call `queryOrganizations` and pass the userId myself.

**Comment by GoPro16** [comment]
I would just add that boolean check in the config to see if the `params.userId` is there and if so then early return ` this.query(queryConfig)` because you already have the required attrs.
