### ISSUE TITLE
NativeForm | Passing undefined Values Result In TypeError

### ISSUE THREAD

**Issue by GoPro16** [Availity/sdk-js#179]
### Current Behavior

When attributes the have `undefined` values are passed to `@availity/native-form` the [`flattenObject`](https://github.com/Availity/sdk-js/blob/master/packages/native-form/flattenObject.js#L14) method gets called and throws a type error when trying to stringify the value.

### Expected behavior

When passing in `undefined` values for attribute keys we should not have native form blow up on us and instead either omit those values from being added or insert a logical default.

### Reproducible example

```js
    const attributes = {
      X_Client_ID: clientId,
      X_XSRF_TOKEN: getToken(),
      spaceId: undefined, // spaceId is undefined
    };
nativeForm(ssoId,attributes)
```

### Suggested solution(s)

1 - Omit the attributes with undefined/null values from being flattened
2 - Provide a default for these in the options object at the end

### Alternatives

- Just fix the code that is calling this to make sure its not passing `undefined/null` in the values.

**Comment by andrectoi** [comment]
If we don't have a safe default for all attributes, then I'd be inclined to go with option 1 here. 

I'd like to think if an attribute got passed in as undefined, we'd want something further down the stream (magneto or whatever i guess) that consumes the form submit to tell us that the attribute is missing.
