### ISSUE TITLE
PATCH method for api-core

### ISSUE THREAD

**Issue by shkn-not-strrd** [Availity/sdk-js#225]
### Current Behavior

Currently, `api-core` wraps the most common `axios` methods, but lacks support for `patch`

### Desired Behavior

`patch` support in `api-core` 

### Suggested Solution

Add `patch` method to `api-core` -- PR incoming.

### Who does this impact? Who is this for?

Users for whom an `update` just doesn't cut it.

### Describe alternatives you've considered

The alternative to adding this support is forcing users who would otherwise be able to leverage `AvApi` to switch to `axios` for their `patch` needs

### Additional context

I've been side-chatting @nylon22 about this, PR coming soon and feedback welcome.

**Comment by nylon22** [comment]
closing via #226
