### ISSUE TITLE
Consistent naming of exports between core, angular, and axios.

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/sdk-js#29]
Currently the name of the exports is not consistent between the different flavors/variations of the project.

| core                | axios              | angular  |
| ------------- | ------------- | -------- |
| (default export) | (default export) | AvApi |
| AvMicroservice | AvMicroservice | AvMicroserviceApi |
| AvLogMessages | logMessagesApi | avLogMessagesApi |
| AvNavigation | navigationApi | avNavigationApi |
| AvNotification | notificationApi | avNotificationsApi |
| AvOrganizations | organizationsApi | avOrganizationsApi |
| AvPermissions | permissionsApi | avPermissionsApi |
| AvProviders | providersApi | avProvidersApi |
| AvPdf | pdfApi | avPdfApi |
| AvProxy | ProxyApi | AvProxyApi |
| AvRegions | regionsApi | avRegionsApi |
| AvSpaces | spacesApi | avSpacesApi |
| AvUsers | userApi | avUsersApi
| AvUserPermissions | userPermissionsApi | avUserPermissionsApi |
| AvFiles | filesApi | avFilesApi |
| AvSettings | settingsApi | avSettingsApi |
| N/A | N/A | avApiOptions |

We should be consistent, which may mean we need to determine if we are going to prefix with `av` or `Av` (or capitalize the first letter if no prefix) and/or postfix with `Api`

**Comment by robmcguinness** [comment]
great analysis. my 2 cents:

- constructors should be capitalized an prefixed with `Av`
- implementations should be lowercased and prefixed with `av`
- postfix with `Api` (for REST) or `Graph` (for GraphQL) when applicable

Thoughts?

**Comment by christieb7007** [comment]
Sounds good

changes:

core | axios | angular
-- | -- | --
(default export) | (default export) | AvApi
AvMicroservice | AvMicroserviceApi | AvMicroserviceApi
AvProxy | AvProxyApi | AvProxyApi
AvLogMessages | avLogMessagesApi | avLogMessagesApi
AvNavigation | avNavigationApi | avNavigationApi
AvNotification | avNotificationApi | avNotificationApi
AvOrganizations | avOrganizationsApi | avOrganizationsApi
AvPermissions | avPermissionsApi | avPermissionsApi
AvProviders | avProvidersApi | avProvidersApi
AvPdf | avPdfApi | avPdfApi
AvRegions | avRegionsApi | avRegionsApi
AvSpaces | avSpacesApi | avSpacesApi
AvUsers | avUserApi | avUsersApi
AvUserPermissions | avUserPermissionsApi | avUserPermissionsApi
AvFiles | avFilesApi | avFilesApi
AvSettings | avSettingsApi | avSettingsApi
N/A | N/A | avApiOptions

**Comment by TheSharpieOne** [comment]
fixed via 96f342d
