### ISSUE TITLE
Remove Object.assign usage

### ISSUE THREAD

**Issue by nylon22** [Availity/sdk-js#299]
### Current Behavior

Object.assign is used at the following locations:

- https://github.com/Availity/sdk-js/blob/c0ab8e94366bc446b176c29070875c7cd760e673/packages/upload-core/src/upload.js#L95
- https://github.com/Availity/sdk-js/blob/c0ab8e94366bc446b176c29070875c7cd760e673/packages/env-var/src/index.js#L58
- https://github.com/Availity/sdk-js/blob/c0ab8e94366bc446b176c29070875c7cd760e673/packages/env-var/src/index.js#L66
- https://github.com/Availity/sdk-js/blob/master/packages/exceptions-core/src/index.js#L123

`Object.assign` is not supported in IE: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

### Expected behavior

Object.assign is not used

### Suggested solution(s)

We either polyfill Object.assign or use the spread operator. or perhaps use the `extend` method from `lodash`. I'm partial to the spread operator.

**Comment by jordan-a-young** [comment]
I vote for using the spread operator too. Looks like it should cover the cases listed.
