### ISSUE TITLE
Wrong return types of `resolveUrl` function

### ISSUE THREAD

**Issue by SettingDust** [Availity/sdk-js#486]
https://github.com/Availity/sdk-js/blob/master/packages/resolve-url/src/resolve-url.d.ts#L6
https://github.com/availity/sdk-js/blob/master/packages/resolve-url/src/relative-to-absolute.d.ts#L3
Should be string due to https://github.com/availity/sdk-js/blob/master/packages/resolve-url/src/relative-to-absolute.js#L123

**Comment by jordan-a-young** [comment]
I opened a PR to fix the types
