### ISSUE TITLE
Npm is released in ES6 causing build failures for projects not using babel-preset-0

### ISSUE THREAD

**Issue by jsarman** [Availity/sdk-js#61]
When another project depends on the library that uses a babel-preset that is greater than 0, the production build can fail with error like 
`Failed to minify the code from this file:  ./node_modules/@availity/api-core/src/api.js:5 `
Specifically this is occurring from a project using react-scripts.  
See http://bit.ly/2tRViJ9 which recommends compiling npm packages to  ES5 for at least a few more years until the ecosystem catches up.

**Comment by robmcguinness** [comment]
Hi @jsarman,

This was intentional. Toolkits like `create-react-app` and `availity-workflow` are configured to consume libraries that are written in ES6. We should probably update the docs to make that clear. All our libs are written and published this way.

**Comment by jsarman** [comment]
@robmcguinness 
create-react-app is not at level babel-preset-stage-0 since some features may not be promoted.  This causes any app that is built with create-react-app to either need to eject or to transpile the dependencies before attempting a production build.  I do not disagree with ES6, but maybe we should consider building core libraries using babel-preset-stage-3.

**Comment by robmcguinness** [comment]
ref: https://github.com/facebook/create-react-app/pull/3776

**Comment by robmcguinness** [comment]
This should be supported by CRA now
