### ISSUE TITLE
Relative Location Header

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/sdk-js#77]
Currently the location header returned in the response (which indicates to poll) expects a fully qualified URL (or absolute URL). Per the HTTP spec, a relative URL can be provided and should be supported

https://github.com/Availity/sdk-js/blob/77b69f24e59370b31e7cf733cce48f8f21f0e665/packages/api-core/src/api.js#L119-L129

The library should check for relative URLs and return a fully qualified URL to be polled.

**Comment by KaseyPowers** [comment]
Wouldn't a relative URL given here be treated the same as the relative URLs we generate for the initial call? 

Is this the reason we have [this](https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/ms.js#L29) in our ms api definition?

**Comment by TheSharpieOne** [comment]
When we get back a relative url in the location header, such as `abcdefg`, we make a request to that url as if it was relative to the current path/page when it should be based on the original request url.
Example:
Current page: `/current/browser/page`
Original API: `/api/v1/uploads/resumeable/`
Response Location header: `abcdefg`

Where it currently polls: `/current/browser/abcdefg`
Where it should poll: `/api/v1/uploads/resumeable/abcdefg`

For microservices, we (for some reason) just use the same url no matter what the location header is IIRC.
