### ISSUE TITLE
api swallows http error??

### ISSUE THREAD

**Issue by robmcguinness** [Availity/sdk-js#79]
it seems we are always resolving successfully when making http request. if so, code should be modified to throw error so that `try/catch` works when `async/await`. This would be breaking change.

https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/api.js#L179

```js
request(config, afterResponse) {
  if (config.polling) {
    config.attempt = config.attempt || 0;
    config.attempt += 1;
  }

  return this.http(config)
    .then(response => this.onResponse(response, afterResponse))
    .catch(error => {
      const response = this.getError(error);
      // throw here ??? <<<===
      return afterResponse ? afterResponse(response) : response;
    });
}
```

**Comment by TheSharpieOne** [comment]
Also, `this.getError` doesn't seem to do anything useful.
https://github.com/Availity/sdk-js/blob/4595a86fd1795f6029443c8fa6e754f0cc662951/packages/api-core/src/api.js#L162-L168

if `error.response` exists, it will return it... else it will return `undefined` (and in a very awkward way)

**Comment by robmcguinness** [comment]
https://github.com/Availity/sdk-js/pull/80
