### ISSUE TITLE
`AvApi` Github Page not working

### ISSUE THREAD

**Issue by adrian-santos** [Availity/sdk-js#92]
This Github page is not working: [https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/README.md](https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/README.md)

**Comment by GoPro16** [comment]
Where are you accessing the link from because it should be:
(https://github.com/Availity/sdk-js/blob/master/packages/api-core/README.md)[https://github.com/Availity/sdk-js/blob/master/packages/api-core/README.md]

**Comment by adrian-santos** [comment]
Here: [https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/resources/README.md#intro](https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/resources/README.md#intro)

**Comment by GoPro16** [comment]
Ah okay will fix that.

**Comment by GoPro16** [comment]
Fixed
